### ISSUE TITLE
Submit Graphgist Validation

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#22]
There should be user-friendly validation on the "Submit a GraphGist" page. User should receive a message like "Please enter a URL" or something like that instead of 500 error. 

In the cases below, I entered some string like "i'm a url" or "www.google.com" or no string into the URL field and something or nothing into the title. 

I was not logged in. 

Bad URL + Preview:
![screenshot 2015-11-30 11 43 25](https://cloud.githubusercontent.com/assets/2731744/11477838/d4bc85e0-9757-11e5-8633-3565630937fb.png)

Title and no URL  + Preview:

![screenshot 2015-11-30 11 43 32](https://cloud.githubusercontent.com/assets/2731744/11477852/df5e0ffa-9757-11e5-976d-f221d579aa94.png)

Title and no URL  + Create:
500 error

No Title and no URL  + Preview/Create button pressed:
500 error

**Comment by cheerfulstoic** [comment]
Fixed, thanks!
