### ISSUE TITLE
Image not showing up in graphgist

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#23]
in this graphgist:

`/graph_gists/9ba113d0-0ea6-4530-877e-4b3b2dd7303c`, I see this image placeholder:

![screenshot 2015-11-30 11 51 37](https://cloud.githubusercontent.com/assets/2731744/11478059/cc8e3a70-9758-11e5-8add-7842809f5f73.png)

However, if I go to the graphgist source, I see the image in the original

![screenshot 2015-11-30 11 50 57](https://cloud.githubusercontent.com/assets/2731744/11478069/e2fc213c-9758-11e5-9069-aae0c851af02.png)

This was graphgist NBA Sneakers and it killed my chrome since it has 100s of queries.

**Comment by cheerfulstoic** [comment]
Hrmm, it's working for me now.  Not sure why, but definitely re-open if you see it again.  It also might have gotten fixed when I re-generated the GraphGists recently
