### ISSUE TITLE
Admin adding new graphgist must select author from dropdown?

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#25]
As an admin I can add a graphist via graph_gists/new. 

I noticed that the author was by default Kenny Bastiani, and that I had to choose an author for my new graphgist. 
![screenshot 2015-11-30 11 56 32](https://cloud.githubusercontent.com/assets/2731744/11478224/b0f85e34-9759-11e5-8893-faf009cf09a7.png)

What should I do if I'm adding a graphgist by some author not on the list?

**Comment by cheerfulstoic** [comment]
I think I fixed the default selection yesterday.  Could you check it out again?

Also, if you want to add a person there's a hidden path at `/people`.

Please re-open if it's still broken

**Comment by whatSocks** [comment]
The default selection is fixed, and I'm able to add a person at /people that makes a new person I can select in the dropdown.
