### ISSUE TITLE
Error on add new graphgist

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#26]
I was getting an error on add graphgist and thought that the lack of "Use Case" might be the culprit so I added one called "Test". 

![screenshot 2015-11-30 12 01 13](https://cloud.githubusercontent.com/assets/2731744/11478318/3bd7a1b8-975a-11e5-9253-376995e3eb91.png)

After submit, I arrived at an error page. Console was empty.

**Comment by cheerfulstoic** [comment]
Good catch, thanks!  You should be able to leave the author/industries/use cases blank.  The issue was that the URL was already in use by another Gist.  I've updated it now so that it gives a better error message.

**Comment by whatSocks** [comment]
I filled out all the fields with data that makes sense and the error message says:

```
raw_url URL could not be resolved / asciidoc can't be blank / html can't be blank
```

I didn't leave anything blank, so I don't know what to change in my submission.

**Comment by whatSocks** [comment]
Oh I got it after trying again: It fails if I put a link to a graph gist, succeeds when i put in a link to an .adoc.

**Comment by cheerfulstoic** [comment]
Hrmm, it should automatically figure it out if you put a link to a graph gist.  Do you know what URL didn't work?
