### ISSUE TITLE
Long URL breaks page on graph_gists/< blah>/edit page

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#28]
![screenshot 2015-11-30 12 19 06](https://cloud.githubusercontent.com/assets/2731744/11478715/97b411fe-975c-11e5-9b63-465f6617386b.png)

/graph_gists/4ffae2d7-8150-45fe-b505-d1a03f9df3f8/edit

**Comment by cheerfulstoic** [comment]
Fixed, thanks!
