### ISSUE TITLE
Icons Broken

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#29]
Icons are broken throughout the site

![screenshot 2015-12-01 13 21 43](https://cloud.githubusercontent.com/assets/2731744/11509874/ae189b18-982e-11e5-8c45-04cef27c8cf5.png)

**Comment by cheerfulstoic** [comment]
For other reasons I've moved the portal to Heroku ( http://graphgist-portal.herokuapp.com/ ) and it seems to be good there, so I'm going to close this
