### ISSUE TITLE
HTML in graph gist title on the add use case screen

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#30]
See graph gist title on the right with the error on the add use case page

![screenshot 2015-12-01 13 26 12](https://cloud.githubusercontent.com/assets/2731744/11510085/c6dff2bc-982f-11e5-952f-74ef56507171.png)

See the same graph gist title minus the error on the use case detail page

![screenshot 2015-12-01 13 26 20](https://cloud.githubusercontent.com/assets/2731744/11510094/e08285fe-982f-11e5-81e4-6f9ffac6d5be.png)

**Comment by cheerfulstoic** [comment]
Fixed!
