### ISSUE TITLE
Error when creating new graph gist

### ISSUE THREAD

**Issue by johnymontana** [neo4j-examples/graphgist_portal#34]
I tried creating a new Graph Gist at this page: http://portal.graphgist.org/submit_graphgist using this URL for the gist: https://gist.githubusercontent.com/johnymontana/b26f5caa35db26be1d37/raw/482bd01a2ffe95feaff74d803e0be9d4f840c316/graphgisttest.adoc

The Preview functionality worked as expected and the gist was rendered properly in the Preview pane, however after clicking "Submit" I was presented with an error "We're sorry but something went wrong." at this url: http://portal.graphgist.org/graph_gists/6e165b14-5a3e-4970-a745-f694bb300548

<img width="1229" alt="screenshot 2015-12-10 11 37 01" src="https://cloud.githubusercontent.com/assets/1222454/11726205/6e11f586-9f32-11e5-8fe0-75795cbb9b30.png">

**Comment by cheerfulstoic** [comment]
Sorry about that!  The GraphGist was successfully created in the DB but it had an error trying to display it.  It should be fixed now, so please try again

**Comment by cheerfulstoic** [comment]
Going to close just to keep things tidy, but please re-open if it's not working for you still
