### ISSUE TITLE
Error when updating email address

### ISSUE THREAD

**Issue by johnymontana** [neo4j-examples/graphgist_portal#35]
Presented with error "1 error prohibited user from being saved: current password can't be blank" with no clear option to enter a password.

Steps to reproduce:
1. authenticate with Twitter
1. Click on "William Lyon" in upper right corner to enter Edit User screen
1. Fill in email address
1. Click "Update"

<img width="1385" alt="screenshot 2015-12-10 11 41 43" src="https://cloud.githubusercontent.com/assets/1222454/11726634/639f8620-9f34-11e5-827a-a6623fc0dce5.png">

**Comment by cheerfulstoic** [comment]
Fixed, thanks!
