### ISSUE TITLE
Full graph is shown after query using //graph

### ISSUE THREAD

**Issue by johnymontana** [neo4j-examples/graphgist_portal#37]
In this graphgist: http://portal.graphgist.org/graph_gists/488fda91-0cae-4545-b3df-9fa03bd1f78d I define a cypher query and then use `//graph` which I expect to show the results of the query as a graph:

~~~
[source,cypher]
----
MATCH (luke:Person {name: "Luke Skywalker"})
MATCH (luke)-[:PILOTS]->(vehicle)-[:MANUFACTURED_BY]->(m:Manufacturer)
MATCH (vehicle)-[:APPEARS_IN]->(f:Film)
RETURN luke,vehicle,m,f
----
//graph
~~~

However this displays the entire graph, not just the results of the query. I was expecting just a handful of nodes, instead of every node:

<img width="1443" alt="screenshot 2015-12-11 13 03 24" src="https://cloud.githubusercontent.com/assets/1222454/11755942/ecdf6726-a00a-11e5-9436-e21b213cf9eb.png">

Is this the expected behavior?

**Comment by jexp** [comment]
@johnymontana the correct syntax for only showing the query results is : `//graph_result`
