### ISSUE TITLE
Fix graph result syntax in graph gist example page

### ISSUE THREAD

**Issue by johnymontana** [neo4j-examples/graphgist_portal#39]
The syntax to show results of a query is `//graph_result`, however the example gist in this page http://portal.graphgist.org/about just uses `//graph`

**Comment by cheerfulstoic** [comment]
I believe they both do the same thing

**Comment by jexp** [comment]
They don't do the same thing.

* `//graph` always renders the **full** graph.
* `//graph_result` **only** renders the query results.

**Comment by johnymontana** [comment]
I still get the full graph when using `//graph_result`.  See this gist for an example: http://portal.graphgist.org/graph_gists/0d2e549b-59b6-48b1-997a-ba8bc4dbabbf

~~~
[source,cypher]
----
MATCH (p:Planet)<-[:TAKES_PLACE_ON]-(f:Film)
RETURN p,f
----

//graph_result
~~~

renders the full graph instead of just the query results:

<img width="946" alt="screenshot 2015-12-12 12 18 49" src="https://cloud.githubusercontent.com/assets/1222454/11763737/c206e928-a0ca-11e5-9cfd-631ca6d51ea2.png">

**Comment by cheerfulstoic** [comment]
Fixed now, sorry about that!

I wish I had known you were importing data from SWAPI.  I already wrote a script to do that a while back ;)  I often use the DB as a demo.  I also don't think that SWAPI is exactly the data from Wookiepedia.  There isn't very much data in SWAPI.  I think he just collected some sample data and imported it into his own database and then made a JSON front-end for fun.
