### ISSUE TITLE
Code Block Formatting

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#42]
Cypher code comes out nice. 

"plain" code blocks come out less blocked on the graph gist as opposed to when built with asciidoctor. 

Building locally with asciidoctor:

![screenshot 2015-12-17 11 34 43](https://cloud.githubusercontent.com/assets/2731744/11875368/498b02e0-a4b2-11e5-8c21-987606fc0cdd.png)

In graph gist:

![screenshot 2015-12-17 11 36 00](https://cloud.githubusercontent.com/assets/2731744/11875388/5ba0dd88-a4b2-11e5-826e-906613873d8d.png)

**Comment by cheerfulstoic** [comment]
Fixed, thanks!
