### ISSUE TITLE
Clicking "Update Now" on author page -> error

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#78]
I clicked "update now" on an author page (and also category pages) and got a 500 error

![screenshot 2016-03-08 09 42 44](https://cloud.githubusercontent.com/assets/2731744/13604740/2d51e256-e512-11e5-856a-fe0cc658dc05.png)

**Comment by cheerfulstoic** [comment]
Ah, good point.  We shouldn't have "Update Now" on author pages (or any non-gist pages), thanks!

**Comment by cheerfulstoic** [comment]
Done, thanks!
