### ISSUE TITLE
[bug] category icons should show uploaded image if there is one

### ISSUE THREAD

**Issue by whatSocks** [neo4j-examples/graphgist_portal#80]
current: category icons are default icons
expected: if i upload an image for a particular category, i should see them when looking at a grid cell. In the image below is default icon. 

![screenshot 2016-03-08 10 14 24](https://cloud.githubusercontent.com/assets/2731744/13605640/8daa595e-e516-11e5-9e4d-0304827102f2.png)

**Comment by cheerfulstoic** [comment]
Fixed, thanks!
